/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import librarymanagement.Data.Book;
import librarymanagement.Data.TransactionItem;
import librarymanagement.Data.User;
import librarymanagement.DataConnection.BookDataConnection;
import librarymanagement.DataConnection.TransactionDataConnection;
import librarymanagement.DataConnection.UserDataConnection;

public class TransactionForm extends javax.swing.JDialog {

    HashMap<String, Book> booksMap = new HashMap<>();
    HashMap<String, User> usersMap = new HashMap<>();
    
    TransactionItem transactionItem = null;
    
    /**
     * Creates new form FormBorrowBook
     */
    public TransactionForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initializeConnections();
    }
    
    private void initialize(){
        initializeControls();
        
        if (!isInsertMode()){
            isbnComboBox.setSelectedItem(transactionItem.bookIsbn);
            userIdComboBox.setSelectedItem(transactionItem.userId);
            checkInDatePicker.setDate(transactionItem.checkInDate);
            checkOutDatePicker.setDate(transactionItem.checkOutDate);
            statusComboBox.setSelectedItem(transactionItem.status);
        }
    }
    
    private void initializeConnections(){
        booksMap.put("", null);
        BookDataConnection bookDataConnection = new BookDataConnection ();        
        for(Book book : bookDataConnection.getAllBooks())
            booksMap.put(book.isbn, book);
        
        usersMap.put("", null);
        UserDataConnection userDataConnection = new UserDataConnection();
        for(User user : userDataConnection.getAllUsers())
            usersMap.put(user.id, user);
    }

    private void initializeControls(){
        isbnComboBox.removeAllItems();
        
        for(String bookId : booksMap.keySet())
            isbnComboBox.addItem(bookId);

        userIdComboBox.removeAllItems();
        
        for(String userId : usersMap.keySet())
            userIdComboBox.addItem(userId);

        Date today = Calendar.getInstance().getTime();
        checkInDatePicker.setDate(today);
        checkOutDatePicker.setDate(today);
    }
    
    private boolean isInsertMode(){
        return transactionItem == null;
    }

    public void setTransactionItem(TransactionItem item){
        this.transactionItem = item;
    }
    
    private void saveToDb(){
        boolean isInsert = isInsertMode();
        if (isInsert)
            transactionItem = new TransactionItem();
        
        transactionItem.bookIsbn = (String)isbnComboBox.getSelectedItem();
        transactionItem.bookTitle = judulBukuTextField.getText();
        transactionItem.userId = (String)userIdComboBox.getSelectedItem();
        transactionItem.userName = userNameTextField.getText();
        transactionItem.checkInDate = checkInDatePicker.getDate();
        transactionItem.checkOutDate = checkOutDatePicker.getDate();
        transactionItem.status = (String)statusComboBox.getSelectedItem();
        
        TransactionDataConnection dataConnection = new TransactionDataConnection();
        
        if (isInsert)
            dataConnection.insertData(transactionItem);
        else
            dataConnection.updateData(transactionItem);
        
        JOptionPane.showMessageDialog(this, "Data Pinjam telah berhasil disimpan!");
        dispose();
    }
    
    private void onIsbnComboBoxChanged(String selectedIsbn){
        Book selectedBook = booksMap.get(selectedIsbn);
        if (selectedBook != null)
            judulBukuTextField.setText(selectedBook.title);
    }
    
    private void onUserIdComboBoxChanged(String selectedId){
        User selectedUser = usersMap.get(selectedId);
        if (selectedUser != null)
            userNameTextField.setText(selectedUser.name);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        judulBukuTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        savePinjamButton = new javax.swing.JButton();
        cancelPinjamButton = new javax.swing.JButton();
        checkOutDatePicker = new org.jdesktop.swingx.JXDatePicker();
        checkInDatePicker = new org.jdesktop.swingx.JXDatePicker();
        isbnComboBox = new javax.swing.JComboBox<>();
        userIdComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Peminjaman Buku");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel2.setText("ISBN");

        jLabel3.setText("Judul Buku");

        jLabel4.setText("ID Peminjam");

        jLabel5.setText("Nama");

        jLabel6.setText("Tanggal Pinjam");

        jLabel7.setText("Tanggal Kembali");

        judulBukuTextField.setEditable(false);

        userNameTextField.setEditable(false);

        savePinjamButton.setText("Simpan");
        savePinjamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePinjamButtonActionPerformed(evt);
            }
        });

        cancelPinjamButton.setText("Batal");
        cancelPinjamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPinjamButtonActionPerformed(evt);
            }
        });

        isbnComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                isbnComboBoxItemStateChanged(evt);
            }
        });

        userIdComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                userIdComboBoxItemStateChanged(evt);
            }
        });

        jLabel8.setText("Status");

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dipinjam", "Dikembalikan", "Melewati Batas" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savePinjamButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelPinjamButton))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(88, 88, 88)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(45, 45, 45)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(judulBukuTextField)
                                .addComponent(isbnComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(userIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkOutDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(statusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(userNameTextField)
                                .addComponent(checkInDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(isbnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(judulBukuTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(userIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkInDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(checkOutDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelPinjamButton)
                    .addComponent(savePinjamButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void savePinjamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePinjamButtonActionPerformed
        saveToDb();
    }//GEN-LAST:event_savePinjamButtonActionPerformed

    private void cancelPinjamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPinjamButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelPinjamButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        initialize();
    }//GEN-LAST:event_formWindowOpened

    private void isbnComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_isbnComboBoxItemStateChanged
        onIsbnComboBoxChanged((String)evt.getItem());
    }//GEN-LAST:event_isbnComboBoxItemStateChanged

    private void userIdComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_userIdComboBoxItemStateChanged
        onUserIdComboBoxChanged((String)evt.getItem());
    }//GEN-LAST:event_userIdComboBoxItemStateChanged
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TransactionForm dialog = new TransactionForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelPinjamButton;
    private org.jdesktop.swingx.JXDatePicker checkInDatePicker;
    private org.jdesktop.swingx.JXDatePicker checkOutDatePicker;
    private javax.swing.JComboBox<String> isbnComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField judulBukuTextField;
    private javax.swing.JButton savePinjamButton;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JComboBox<String> userIdComboBox;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
